# Project 3 Assignment

## Assignment Overview & Instructions

The objective of project 3 is to perform keyword network analysis and word frequency
analysis.  
Please complete the following 7 tasks in this assessment, using the instructions indicated below.   

**Note:** You may create your own custom functions if necessary to complete the tasks.

### Task 1: Import the Dataset for use in your Notebook.

You can find the source dataset [here](https://drive.google.com/file/d/1YJe45YXo0xSkFClGPBhKYLzupFEyGadK/view?usp=sharing)

In [1]:
## YOUR CODE HERE

import pandas as pd

df = pd.read_csv('data/keywords_data.csv')

df.head()

,Title,Keyword 1,Keyword 2,Keyword 3,Keyword 4,Keyword 5,Keyword 6,Keyword 7,Keyword 8,Keyword 9,Keyword 10,Keyword 11,Keyword 12
0,Feb/03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Meta-Analyses of Financial Performance and Equ...,EQUITY,ORGANIZATIONAL sociology,PERFORMANCE,META-analysis,PSYCHOMETRICS,ORGANIZATIONAL research,FINANCIAL performance,AGENCY theory,ORGANIZATIONAL effectiveness,ORGANIZATIONAL behavior,CORPORATE governance,NaN
3,"Home Country Environments, Corporate Diversifi...",DIVERSIFICATION in industry,BUSINESS planning,PERFORMANCE standards,EMPLOYEES -- Rating of,CORPORATE culture,STRATEGIC planning,ORGANIZATIONAL effectiveness,MANAGEMENT science,MANAGEMENT research,PRODUCT management,NaN,NaN
4,Safeguarding Investments in Asymmetric Interor...,INTERORGANIZATIONAL relations,INTERGROUP relations,BUSINESS communication,INVESTMENTS,SUPPLY chains,KNOWLEDGE management,INTERORGANIZATIONAL networks,CORPORATE governance,GROUP decision making,INTELLECTUAL capital,NaN,NaN

### **Task 2:**  Write a Python code to extract keyword data from the above file. 
Write a Python code to extract keyword data from the above file and convert it to a weighted adjacency matrix. See the figure below to understand the process

![Task Two - Adjacency matrix](Task%202%20-%20Figure%201.png)

In [9]:
## YOUR CODE HERE
import nltk
import string
import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
import re
nltk.download('punkt_tab', quiet ='True')
from nltk.tokenize import word_tokenize
nltk.download('stopwords', quiet ='True')

# Extract and preprocess keywords
keyword_cols = [f'Keyword {i}' for i in range (1, 13)]

keyword_df = df[keyword_cols].dropna(how='all')

all_keywords = []
for index, row in keyword_df.iterrows():
    keywords = row.dropna().astype(str).str.lower().str.strip().tolist()
    if keywords:
        all_keywords.append(keywords)

# Generate co-occurence pairs
co_occurrence_pairs = list()
for tokens in all_keywords:
    filtered_tokens = sorted(set(tokens))  # remove duplicate & sort
    co_occurrence_pairs += [
        (filtered_tokens[i], filtered_tokens[j])
        for i in range(len(filtered_tokens))
        for j in range(i + 1, len(filtered_tokens))
    ]

# weight pairs using frequency distribution
weighted_co_occurrences = nltk.FreqDist(co_occurrence_pairs)
print(f'weighted_co_occurrences: {weighted_co_occurrences.most_common(10)}...')

unique_keywords = sorted(set(word for pair in weighted_co_occurrences.keys() for word in pair))
print(f'Unique Keywords found: {len(unique_keywords)}')

adj_df = pd.DataFrame(0, index = unique_keywords, columns = unique_keywords)

for (kw1, kw2), weight in weighted_co_occurrences.items():
    adj_df.at[kw1,kw2] = weight
    adj_df.at[kw2,kw1] = weight

print('\nAdjacency Matrix shape' , adj_df.shape)

adj_df.head()

weighted_co_occurrences: [(('organizational behavior', 'organizational effectiveness'), 11), (('organizational behavior', 'organizational structure'), 9), (('organizational behavior', 'personnel management'), 8), (('management science', 'organizational behavior'), 7), (('corporate governance', 'organizational behavior'), 6), (('organizational behavior', 'organizational sociology'), 6), (('decision making', 'organizational behavior'), 6), (('organizational effectiveness', 'organizational structure'), 6), (('industrial relations', 'organizational behavior'), 5), (('organizational behavior', 'organizational change'), 5)]...
Unique Keywords found: 248

Adjacency Matrix shape (248, 248)

,agency theory,aggression (psychology),ambivalence,anger in the workplace,behavioral research,boards of directors,break-even analysis,burnout (psychology),business communication,business enterprises,...,violence in the workplace,wage payment systems,wages,women -- employment,women employees,work & family,work attitudes,work environment,work environment -- psychological aspects,workflow
agency theory,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
aggression (psychology),0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,1,2,0,0
ambivalence,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
anger in the workplace,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,1,0,0
behavioral research,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### **Task 3:**  Read the adjacency matrix and convert it into a weighted network

In [ ]:
## YOUR CODE HERE

### **Task 4:**  Compute node degree and strength

In [ ]:
## YOUR CODE HERE

### **Task 5:**  Show the top 10 nodes by degree and top 10 nodes by strength

In [ ]:
## YOUR CODE HERE

### **Task 6:** Show the top 10 node pairs by weight

In [ ]:
## YOUR CODE HERE

### **Task 7:** Plot strength on y-axis and degree on x-axis

In [ ]:
## YOUR CODE HERE

## Submitting your Project

Once you've completed your project, it's time to submit your work for grading.   
This week, you will submit your code file `Project 3.ipynb` to the following Staff Graded Assignment for review.  

In order to submit your work, please follow the steps below:
1. Verify you've saved your work using the `Save` button within the Jupyter Notebook 
2. Download this notebook using the `File` -> `Download As` -> Choose the `Notebook (.ipynb)` format.
3. Access the following Step 2: Submit Project 3 item.
4. Complete all prompted fields, and upload your Jupyter Notebook file (Project 3.ipynb) in the indicated field.
5. Submit your notebook to "Step 2: Submit Project 3" by the deadline indicated within your course view for the Project 3 Assignment item.

Congratulations on completing the Project 3 Assignment!